# Site settings
author: Vedran Sehovic
title: My Coding Journey
header-img: img/home-bg.png
email: vedran.sehovic@gmail.com
copyright_name: Vedran Sehovic
description: > # this means to ignore newlines until "baseurl:"
  Citius, Altius, Fortius
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vedransehovic

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
